version: '3.8'

services:
  mariadb:
    container_name: mariadb
    image: mariadb
    networks:
      - inception
    build: 
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    expose:
      - "3306"
    restart: unless-stopped
    
  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    build: 
      context: ./requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "443:443"
      - "80:80"
    restart: unless-stopped
  wordpress:
    container_name: wordpress
    image: wordpress
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    build: 
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    expose:
      - "9000"
    depends_on:
      - mariadb
    restart: unless-stopped

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/Users/russelenc/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none' 
      o: 'bind'
      device: '/Users/russelenc/data/mariadb'

networks:
  inception:
    driver: bridge
